server {
    listen 80;
    server_name localhost;

    root /usr/share/nginx/html;
    index index.html;

    # Standardservice für normale Dateien
    location / {
        try_files $uri $uri/ /index.html;
    }

    # Header für vorkomprimierte Unity WebGL-Dateien
    location ~* \.data\.gz$ {
        add_header Content-Encoding gzip;
        add_header Content-Type application/octet-stream;
    }

    location ~* \.wasm\.gz$ {
        add_header Content-Encoding gzip;
        add_header Content-Type application/wasm;
    }

    location ~* \.js\.gz$ {
        add_header Content-Encoding gzip;
        add_header Content-Type application/javascript;
    }
}
